apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  volumes:
    - name: pvc1
      persistentVolumeClaim:
        claimName: data1      
  containers:
  - name: ubuntu
    image: ubuntu:16.04
    volumeMounts:
      - mountPath: /mnt
        name: pvc1
    command: ["/usr/bin/tail","-f","/dev/null"]
