apiVersion: v1
kind: Pod
metadata:
  name: webapl
spec:
  containers:
    - name: webapl
    image: takeshi1215/webapl:0.1
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000
      initialDeleySecounds: 3
      periodSecounds: 5
    readinessProbe:
      httpGet:
        path: /ready
        port: 3000
      initialDeleySecounds: 15
      periodSecounds: 6